// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4d90q-mu-B3oHGKaD3mwK9EiHJvEuSI',
    appId: '1:718553496615:web:afc620ec5f8de7104b2202',
    messagingSenderId: '718553496615',
    projectId: 'seenchatapp',
    authDomain: 'seenchatapp.firebaseapp.com',
    storageBucket: 'seenchatapp.appspot.com',
    measurementId: 'G-66ZESWYSSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxou91pwas2DHKCQEI6PZtDpruNJieL-8',
    appId: '1:718553496615:android:dadf62b2a8908f644b2202',
    messagingSenderId: '718553496615',
    projectId: 'seenchatapp',
    storageBucket: 'seenchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxBWM5onlqHgqr3UkzuO1hubEmLlVNPY',
    appId: '1:718553496615:ios:70365805809cdc0c4b2202',
    messagingSenderId: '718553496615',
    projectId: 'seenchatapp',
    storageBucket: 'seenchatapp.appspot.com',
    iosBundleId: 'com.example.seen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoxBWM5onlqHgqr3UkzuO1hubEmLlVNPY',
    appId: '1:718553496615:ios:70365805809cdc0c4b2202',
    messagingSenderId: '718553496615',
    projectId: 'seenchatapp',
    storageBucket: 'seenchatapp.appspot.com',
    iosBundleId: 'com.example.seen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4d90q-mu-B3oHGKaD3mwK9EiHJvEuSI',
    appId: '1:718553496615:web:22636da0e23dd6a64b2202',
    messagingSenderId: '718553496615',
    projectId: 'seenchatapp',
    authDomain: 'seenchatapp.firebaseapp.com',
    storageBucket: 'seenchatapp.appspot.com',
    measurementId: 'G-CNCJPWN7V7',
  );
}
